name: Deploy via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build static site
        run: CI=false npm run build 

      - name: Deploy (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp://agime-fanch@ftp.cluster006.hosting.ovh.net/
          username: ${{ secrets.FTPLOGIN }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          port: 21
          local-dir: build/
          server-dir: /
          dangerous-clean-slate: true